// This file is @generated by prost-build.
/// Request to create a new repository. The caller pre-generates `id` and
/// `default_branch_id` so retries are idempotent — a duplicate `id` yields
/// ALREADY_EXISTS unless the call is byte-for-byte the same as the prior
/// success, in which case the server returns the existing record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryCreateRequest {
    /// Caller-pre-generated repository id (typically a UUIDv7).
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// Human-readable repository name. Must satisfy the validation rules in
    /// `lore-revision::repository::is_valid_name` and must not collide with
    /// any existing repository: `/`-separated segments of ASCII alphanumerics,
    /// `-`, `_` and `.`, where no segment is empty or starts with `.`.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Free-form description, stored verbatim in the repository metadata.
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Caller-pre-generated default branch id (typically a UUIDv7).
    #[prost(bytes = "bytes", tag = "4")]
    pub default_branch_id: ::prost::bytes::Bytes,
    /// Default branch name, e.g. "main". Subject to the same name-validation
    /// limits as a regular branch name.
    #[prost(string, tag = "5")]
    pub default_branch_name: ::prost::alloc::string::String,
    /// Identity to attribute as the repository creator. If unset, the server
    /// uses the authenticated JWT identity. If set, the caller must have
    /// permission to attribute repositories to other identities.
    #[prost(string, optional, tag = "6")]
    pub creator: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for RepositoryCreateRequest {
    const NAME: &'static str = "RepositoryCreateRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryCreateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryCreateRequest".into()
    }
}
/// Response containing the freshly-created repository record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryCreateResponse {
    /// Full Repository record including server-assigned `created` timestamp
    /// and the server-assigned metadata pointer.
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<crate::lore::model::v1::Repository>,
}
impl ::prost::Name for RepositoryCreateResponse {
    const NAME: &'static str = "RepositoryCreateResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryCreateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryCreateResponse".into()
    }
}
/// Request to hard-delete a repository by id. Names are not used here
/// because they may have been recycled after a prior delete.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryDeleteRequest {
    /// Repository id obtained from a prior RepositoryGet / RepositoryList.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryDeleteRequest {
    const NAME: &'static str = "RepositoryDeleteRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryDeleteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryDeleteRequest".into()
    }
}
/// Response carrying the last-known repository record. Repositories are
/// hard-deleted, so this is the caller's only chance to see the deleted
/// record's id, name and creator.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryDeleteResponse {
    /// Repository record as it was immediately before deletion.
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<crate::lore::model::v1::Repository>,
}
impl ::prost::Name for RepositoryDeleteResponse {
    const NAME: &'static str = "RepositoryDeleteResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryDeleteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryDeleteResponse".into()
    }
}
/// Request to look up a repository by id or by name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryGetRequest {
    /// Lookup mode.
    #[prost(oneof = "repository_get_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<repository_get_request::Query>,
}
/// Nested message and enum types in `RepositoryGetRequest`.
pub mod repository_get_request {
    /// Lookup mode.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Lookup by repository id.
        #[prost(bytes, tag = "1")]
        Id(::prost::bytes::Bytes),
        /// Lookup by repository name.
        #[prost(string, tag = "2")]
        Name(::prost::alloc::string::String),
    }
}
impl ::prost::Name for RepositoryGetRequest {
    const NAME: &'static str = "RepositoryGetRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryGetRequest".into()
    }
}
/// Response containing the resolved repository record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryGetResponse {
    /// Repository record matching the lookup.
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<crate::lore::model::v1::Repository>,
}
impl ::prost::Name for RepositoryGetResponse {
    const NAME: &'static str = "RepositoryGetResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryGetResponse".into()
    }
}
/// Request to stream repositories the caller is authorised to see, with
/// optional filters. When auth is configured the server first consults
/// the auth service for the caller's permitted resource set; when auth is
/// off the server returns all locally-known repositories.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryListRequest {
    /// If set, only repositories whose `creator` field is an exact
    /// byte-for-byte case-sensitive match are emitted.
    #[prost(string, optional, tag = "1")]
    pub creator: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for RepositoryListRequest {
    const NAME: &'static str = "RepositoryListRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryListRequest".into()
    }
}
/// One-per-stream-message response carrying a single repository record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryListResponse {
    /// A repository matching the request's filters and the caller's
    /// authorisation.
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<crate::lore::model::v1::Repository>,
}
impl ::prost::Name for RepositoryListResponse {
    const NAME: &'static str = "RepositoryListResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryListResponse".into()
    }
}
/// Request for a cheap hash-only read of a repository's metadata pointer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataGetRequest {
    /// Repository id.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataGetRequest {
    const NAME: &'static str = "RepositoryMetadataGetRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryMetadataGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryMetadataGetRequest".into()
    }
}
/// Response carrying the current metadata hash.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataGetResponse {
    /// Current metadata pointer.
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataGetResponse {
    const NAME: &'static str = "RepositoryMetadataGetResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryMetadataGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryMetadataGetResponse".into()
    }
}
/// Request for a compare-and-swap update of a repository's metadata
/// pointer. The proposed metadata blob must already be addressable in CAS
/// before issuing this call; the server validates that any Address-typed
/// values inside the blob reference live blobs and refuses to install a
/// blob that mutates read-only fields (name, creator, created).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataSetRequest {
    /// Repository id.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// The metadata hash the caller expects to be currently set. The server
    /// compares this to the actual current value and only swaps on match.
    #[prost(bytes = "bytes", tag = "2")]
    pub expected: ::prost::bytes::Bytes,
    /// The metadata hash to install if the CAS succeeds.
    #[prost(bytes = "bytes", tag = "3")]
    pub updated: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataSetRequest {
    const NAME: &'static str = "RepositoryMetadataSetRequest";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryMetadataSetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryMetadataSetRequest".into()
    }
}
/// Response always returned with gRPC OK regardless of CAS hit or miss. On
/// a successful CAS, response.metadata == request.updated. On a CAS miss,
/// response.metadata reflects the unchanged prior value; the caller compares
/// response.metadata vs request.updated to detect the miss and retry.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryMetadataSetResponse {
    /// The repository's current metadata pointer after the call.
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for RepositoryMetadataSetResponse {
    const NAME: &'static str = "RepositoryMetadataSetResponse";
    const PACKAGE: &'static str = "lore.repository.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.repository.v1.RepositoryMetadataSetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.repository.v1.RepositoryMetadataSetResponse".into()
    }
}
/// Generated client implementations.
pub mod repository_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Baseline repository-management service. Carries the lifecycle and
    /// metadata-pointer primitives — repository create / delete, lookup, list,
    /// and CAS update of the repository metadata pointer. The repository
    /// metadata blob itself is read/written through CAS storage like any other
    /// content; this service only mediates the pointer to its current head.
    #[derive(Debug, Clone)]
    pub struct RepositoryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RepositoryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RepositoryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RepositoryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RepositoryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Create a new repository together with its default branch. The caller
        /// pre-generates `id` and `default_branch_id` for retry idempotency.
        /// Re-issuing the same `id` (or `name`) returns ALREADY_EXISTS unless the
        /// call is byte-for-byte the same as the prior one, in which case it
        /// returns the existing record (idempotent retry).
        pub async fn repository_create(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryCreate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Hard-delete a repository: clears the name → id mapping, zeroes the
        /// metadata pointer, and tears down all branches.
        pub async fn repository_delete(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryDeleteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryDelete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryDelete",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Look up a repository by id or by name.
        pub async fn repository_get(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream all repositories the caller is authorised to see.
        pub async fn repository_list(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryListRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RepositoryListResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryList",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Cheap hash-only read of a repository's current metadata pointer.
        pub async fn repository_metadata_get(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryMetadataGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryMetadataGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryMetadataGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryMetadataGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Compare-and-swap update of a repository's metadata pointer. CAS miss is
        /// signalled in-band via the response, never as a non-OK gRPC status.
        pub async fn repository_metadata_set(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryMetadataSetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryMetadataSetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.RepositoryService/RepositoryMetadataSet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.RepositoryService",
                        "RepositoryMetadataSet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod repository_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RepositoryServiceServer.
    #[async_trait]
    pub trait RepositoryService: std::marker::Send + std::marker::Sync + 'static {
        /// Create a new repository together with its default branch. The caller
        /// pre-generates `id` and `default_branch_id` for retry idempotency.
        /// Re-issuing the same `id` (or `name`) returns ALREADY_EXISTS unless the
        /// call is byte-for-byte the same as the prior one, in which case it
        /// returns the existing record (idempotent retry).
        async fn repository_create(
            &self,
            request: tonic::Request<super::RepositoryCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryCreateResponse>,
            tonic::Status,
        >;
        /// Hard-delete a repository: clears the name → id mapping, zeroes the
        /// metadata pointer, and tears down all branches.
        async fn repository_delete(
            &self,
            request: tonic::Request<super::RepositoryDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryDeleteResponse>,
            tonic::Status,
        >;
        /// Look up a repository by id or by name.
        async fn repository_get(
            &self,
            request: tonic::Request<super::RepositoryGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryGetResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the RepositoryList method.
        type RepositoryListStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RepositoryListResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream all repositories the caller is authorised to see.
        async fn repository_list(
            &self,
            request: tonic::Request<super::RepositoryListRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::RepositoryListStream>,
            tonic::Status,
        >;
        /// Cheap hash-only read of a repository's current metadata pointer.
        async fn repository_metadata_get(
            &self,
            request: tonic::Request<super::RepositoryMetadataGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryMetadataGetResponse>,
            tonic::Status,
        >;
        /// Compare-and-swap update of a repository's metadata pointer. CAS miss is
        /// signalled in-band via the response, never as a non-OK gRPC status.
        async fn repository_metadata_set(
            &self,
            request: tonic::Request<super::RepositoryMetadataSetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryMetadataSetResponse>,
            tonic::Status,
        >;
    }
    /// Baseline repository-management service. Carries the lifecycle and
    /// metadata-pointer primitives — repository create / delete, lookup, list,
    /// and CAS update of the repository metadata pointer. The repository
    /// metadata blob itself is read/written through CAS storage like any other
    /// content; this service only mediates the pointer to its current head.
    #[derive(Debug)]
    pub struct RepositoryServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RepositoryServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RepositoryServiceServer<T>
    where
        T: RepositoryService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.repository.v1.RepositoryService/RepositoryCreate" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryCreateSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::UnaryService<super::RepositoryCreateRequest>
                    for RepositoryCreateSvc<T> {
                        type Response = super::RepositoryCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_create(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryCreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.repository.v1.RepositoryService/RepositoryDelete" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryDeleteSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::UnaryService<super::RepositoryDeleteRequest>
                    for RepositoryDeleteSvc<T> {
                        type Response = super::RepositoryDeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryDeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_delete(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryDeleteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.repository.v1.RepositoryService/RepositoryGet" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryGetSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::UnaryService<super::RepositoryGetRequest>
                    for RepositoryGetSvc<T> {
                        type Response = super::RepositoryGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_get(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.repository.v1.RepositoryService/RepositoryList" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryListSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::ServerStreamingService<super::RepositoryListRequest>
                    for RepositoryListSvc<T> {
                        type Response = super::RepositoryListResponse;
                        type ResponseStream = T::RepositoryListStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_list(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.repository.v1.RepositoryService/RepositoryMetadataGet" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryMetadataGetSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::UnaryService<super::RepositoryMetadataGetRequest>
                    for RepositoryMetadataGetSvc<T> {
                        type Response = super::RepositoryMetadataGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryMetadataGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_metadata_get(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryMetadataGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.repository.v1.RepositoryService/RepositoryMetadataSet" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryMetadataSetSvc<T: RepositoryService>(pub Arc<T>);
                    impl<
                        T: RepositoryService,
                    > tonic::server::UnaryService<super::RepositoryMetadataSetRequest>
                    for RepositoryMetadataSetSvc<T> {
                        type Response = super::RepositoryMetadataSetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryMetadataSetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepositoryService>::repository_metadata_set(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryMetadataSetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RepositoryServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.repository.v1.RepositoryService";
    impl<T> tonic::server::NamedService for RepositoryServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod forwarded_repository_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// A service to receive requests forwarded on from another Lore Server,
    /// to perform an RPC on behalf of a client
    #[derive(Debug, Clone)]
    pub struct ForwardedRepositoryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ForwardedRepositoryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ForwardedRepositoryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ForwardedRepositoryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ForwardedRepositoryServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn repository_create(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.repository.v1.ForwardedRepositoryService/RepositoryCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.repository.v1.ForwardedRepositoryService",
                        "RepositoryCreate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod forwarded_repository_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ForwardedRepositoryServiceServer.
    #[async_trait]
    pub trait ForwardedRepositoryService: std::marker::Send + std::marker::Sync + 'static {
        async fn repository_create(
            &self,
            request: tonic::Request<super::RepositoryCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryCreateResponse>,
            tonic::Status,
        >;
    }
    /// A service to receive requests forwarded on from another Lore Server,
    /// to perform an RPC on behalf of a client
    #[derive(Debug)]
    pub struct ForwardedRepositoryServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ForwardedRepositoryServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for ForwardedRepositoryServiceServer<T>
    where
        T: ForwardedRepositoryService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.repository.v1.ForwardedRepositoryService/RepositoryCreate" => {
                    #[allow(non_camel_case_types)]
                    struct RepositoryCreateSvc<T: ForwardedRepositoryService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: ForwardedRepositoryService,
                    > tonic::server::UnaryService<super::RepositoryCreateRequest>
                    for RepositoryCreateSvc<T> {
                        type Response = super::RepositoryCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ForwardedRepositoryService>::repository_create(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RepositoryCreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ForwardedRepositoryServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.repository.v1.ForwardedRepositoryService";
    impl<T> tonic::server::NamedService for ForwardedRepositoryServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
