services:
  lore-server:
    image: ghcr.io/radicalgrimoire/lore/lore:0.8.3.3
    ports:
      - "41337:41337/tcp"
      - "41337:41337/udp"
      - "41339:41339"
    volumes:
      - lore-data:/data
    environment:
      LORE_CONFIG_PATH: /etc/lore/config
      LORE_ENV: docker
      RUST_LOG: info
    restart: unless-stopped

volumes:
  lore-data:
